/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS "config_info";
CREATE TABLE "config_info"
(
    "id"                 int8                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "data_id"            varchar(255) COLLATE "pg_catalog"."default"  NOT NULL,
    "group_id"           varchar(128) COLLATE "pg_catalog"."default",
    "content"            text COLLATE "pg_catalog"."default"          NOT NULL,
    "md5"                varchar(32) COLLATE "pg_catalog"."default",
    "gmt_create"         timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gmt_modified"       timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "src_user"           text COLLATE "pg_catalog"."default",
    "src_ip"             varchar(50) COLLATE "pg_catalog"."default",
    "app_name"           varchar(128) COLLATE "pg_catalog"."default",
    "tenant_id"          varchar(128) COLLATE "pg_catalog"."default"           DEFAULT ''::character varying,
    "c_desc"             varchar(256) COLLATE "pg_catalog"."default",
    "c_use"              varchar(64) COLLATE "pg_catalog"."default",
    "effect"             varchar(64) COLLATE "pg_catalog"."default",
    "type"               varchar(64) COLLATE "pg_catalog"."default",
    "c_schema"           text COLLATE "pg_catalog"."default",
    "encrypted_data_key" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "config_info"."id" IS 'id';
COMMENT ON COLUMN "config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info"."content" IS 'content';
COMMENT ON COLUMN "config_info"."md5" IS 'md5';
COMMENT ON COLUMN "config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "config_info"."c_desc" IS 'configuration description';
COMMENT ON COLUMN "config_info"."c_use" IS 'configuration usage';
COMMENT ON COLUMN "config_info"."effect" IS '配置生效的描述';
COMMENT ON COLUMN "config_info"."type" IS '配置的类型';
COMMENT ON COLUMN "config_info"."c_schema" IS '配置的模式';
COMMENT ON COLUMN "config_info"."encrypted_data_key" IS '密钥';
COMMENT ON TABLE "config_info" IS 'config_info';

-- ----------------------------
-- Records of config_info
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS "config_info_beta";
CREATE TABLE "config_info_beta"
(
    "id"                 int8                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "data_id"            varchar(255) COLLATE "pg_catalog"."default"  NOT NULL,
    "group_id"           varchar(128) COLLATE "pg_catalog"."default"  NOT NULL,
    "app_name"           varchar(128) COLLATE "pg_catalog"."default",
    "content"            text COLLATE "pg_catalog"."default"          NOT NULL,
    "beta_ips"           varchar(1024) COLLATE "pg_catalog"."default",
    "md5"                varchar(32) COLLATE "pg_catalog"."default",
    "gmt_create"         timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gmt_modified"       timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "src_user"           text COLLATE "pg_catalog"."default",
    "src_ip"             varchar(50) COLLATE "pg_catalog"."default",
    "tenant_id"          varchar(128) COLLATE "pg_catalog"."default"           DEFAULT ''::character varying,
    "encrypted_data_key" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "config_info_beta"."id" IS 'id';
COMMENT ON COLUMN "config_info_beta"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_beta"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_beta"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info_beta"."content" IS 'content';
COMMENT ON COLUMN "config_info_beta"."beta_ips" IS 'betaIps';
COMMENT ON COLUMN "config_info_beta"."md5" IS 'md5';
COMMENT ON COLUMN "config_info_beta"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "config_info_beta"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info_beta"."src_user" IS 'source user';
COMMENT ON COLUMN "config_info_beta"."src_ip" IS 'source ip';
COMMENT ON COLUMN "config_info_beta"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "config_info_beta"."encrypted_data_key" IS '密钥';
COMMENT ON TABLE "config_info_beta" IS 'config_info_beta';

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_info_gray
-- ----------------------------
DROP TABLE IF EXISTS "config_info_gray";
CREATE TABLE "config_info_gray"
(
    "id"                 int8                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "data_id"            varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "group_id"           varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "content"            text COLLATE "pg_catalog"."default"         NOT NULL,
    "md5"                varchar(32) COLLATE "pg_catalog"."default",
    "src_user"           text COLLATE "pg_catalog"."default",
    "src_ip"             varchar(100) COLLATE "pg_catalog"."default",
    "gmt_create"         timestamp(3)                                NOT NULL,
    "gmt_modified"       timestamp(3)                                NOT NULL,
    "app_name"           varchar(128) COLLATE "pg_catalog"."default",
    "tenant_id"          varchar(128) COLLATE "pg_catalog"."default"          DEFAULT ''::character varying,
    "gray_name"          varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "gray_rule"          text COLLATE "pg_catalog"."default"         NOT NULL,
    "encrypted_data_key" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "config_info_gray"."id" IS 'id';
COMMENT ON COLUMN "config_info_gray"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_gray"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_gray"."content" IS 'content';
COMMENT ON COLUMN "config_info_gray"."md5" IS 'md5';
COMMENT ON COLUMN "config_info_gray"."src_user" IS 'src_user';
COMMENT ON COLUMN "config_info_gray"."src_ip" IS 'src_ip';
COMMENT ON COLUMN "config_info_gray"."gmt_create" IS 'gmt_create';
COMMENT ON COLUMN "config_info_gray"."gmt_modified" IS 'gmt_modified';
COMMENT ON COLUMN "config_info_gray"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info_gray"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "config_info_gray"."gray_name" IS 'gray_name';
COMMENT ON COLUMN "config_info_gray"."gray_rule" IS 'gray_rule';
COMMENT ON COLUMN "config_info_gray"."encrypted_data_key" IS 'encrypted_data_key';
COMMENT ON TABLE "config_info_gray" IS 'config_info_gray';

-- ----------------------------
-- Records of config_info_gray
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS "config_info_tag";
CREATE TABLE "config_info_tag"
(
    "id"           int8                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "data_id"      varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "group_id"     varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "tenant_id"    varchar(128) COLLATE "pg_catalog"."default"          DEFAULT ''::character varying,
    "tag_id"       varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "app_name"     varchar(128) COLLATE "pg_catalog"."default",
    "content"      text COLLATE "pg_catalog"."default"         NOT NULL,
    "md5"          varchar(32) COLLATE "pg_catalog"."default",
    "gmt_create"   timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gmt_modified" timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "src_user"     text COLLATE "pg_catalog"."default",
    "src_ip"       varchar(50) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "config_info_tag"."id" IS 'id';
COMMENT ON COLUMN "config_info_tag"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_info_tag"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_info_tag"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "config_info_tag"."tag_id" IS 'tag_id';
COMMENT ON COLUMN "config_info_tag"."app_name" IS 'app_name';
COMMENT ON COLUMN "config_info_tag"."content" IS 'content';
COMMENT ON COLUMN "config_info_tag"."md5" IS 'md5';
COMMENT ON COLUMN "config_info_tag"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "config_info_tag"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "config_info_tag"."src_user" IS 'source user';
COMMENT ON COLUMN "config_info_tag"."src_ip" IS 'source ip';
COMMENT ON TABLE "config_info_tag" IS 'config_info_tag';

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS "config_tags_relation";
CREATE TABLE "config_tags_relation"
(
    "id"        int8                                        NOT NULL,
    "tag_name"  varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "tag_type"  varchar(64) COLLATE "pg_catalog"."default",
    "data_id"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "group_id"  varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "nid"       int8                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
)
;
COMMENT ON COLUMN "config_tags_relation"."id" IS 'id';
COMMENT ON COLUMN "config_tags_relation"."tag_name" IS 'tag_name';
COMMENT ON COLUMN "config_tags_relation"."tag_type" IS 'tag_type';
COMMENT ON COLUMN "config_tags_relation"."data_id" IS 'data_id';
COMMENT ON COLUMN "config_tags_relation"."group_id" IS 'group_id';
COMMENT ON COLUMN "config_tags_relation"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "config_tags_relation"."nid" IS 'nid, 自增长标识';
COMMENT ON TABLE "config_tags_relation" IS 'config_tag_relation';

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS "group_capacity";
CREATE TABLE "group_capacity"
(
    "id"                int8                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "group_id"          varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "quota"             int8                                        NOT NULL DEFAULT 0,
    "usage"             int8                                        NOT NULL DEFAULT 0,
    "max_size"          int8                                        NOT NULL DEFAULT 0,
    "max_aggr_count"    int8                                        NOT NULL DEFAULT 0,
    "max_aggr_size"     int8                                        NOT NULL DEFAULT 0,
    "max_history_count" int8                                        NOT NULL DEFAULT 0,
    "gmt_create"        timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gmt_modified"      timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

COMMENT ON COLUMN "group_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "group_capacity"."group_id" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "group_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "group_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."max_aggr_count" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "group_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "group_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "group_capacity"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "group_capacity" IS '集群、各Group容量信息表';

-- ----------------------------
-- Records of group_capacity
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS "his_config_info";
CREATE TABLE "his_config_info"
(
    "id"                 int8                                         NOT NULL,
    "nid"                int8                                         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "data_id"            varchar(255) COLLATE "pg_catalog"."default"  NOT NULL,
    "group_id"           varchar(128) COLLATE "pg_catalog"."default"  NOT NULL,
    "app_name"           varchar(128) COLLATE "pg_catalog"."default",
    "content"            text COLLATE "pg_catalog"."default"          NOT NULL,
    "md5"                varchar(32) COLLATE "pg_catalog"."default",
    "gmt_create"         timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gmt_modified"       timestamp(6)                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "src_user"           text COLLATE "pg_catalog"."default",
    "src_ip"             varchar(50) COLLATE "pg_catalog"."default",
    "op_type"            char(10) COLLATE "pg_catalog"."default",
    "tenant_id"          varchar(128) COLLATE "pg_catalog"."default"           DEFAULT ''::character varying,
    "encrypted_data_key" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "publish_type"       varchar(50) COLLATE "pg_catalog"."default"            DEFAULT 'formal'::character varying,
    "ext_info"           text COLLATE "pg_catalog"."default"
)
;

COMMENT ON COLUMN "his_config_info"."id" IS 'id';
COMMENT ON COLUMN "his_config_info"."nid" IS 'nid, 自增标识';
COMMENT ON COLUMN "his_config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "his_config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "his_config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "his_config_info"."content" IS 'content';
COMMENT ON COLUMN "his_config_info"."md5" IS 'md5';
COMMENT ON COLUMN "his_config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "his_config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "his_config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "his_config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "his_config_info"."op_type" IS 'operation type';
COMMENT ON COLUMN "his_config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "his_config_info"."encrypted_data_key" IS '密钥';
COMMENT ON COLUMN "his_config_info"."publish_type" IS 'publish type gray or formal';
COMMENT ON COLUMN "his_config_info"."ext_info" IS 'ext info';
COMMENT ON TABLE "his_config_info" IS '多租户改造';

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS "permissions";
CREATE TABLE "permissions"
(
    "role"     varchar(50) COLLATE "pg_catalog"."default"  NOT NULL,
    "resource" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "action"   varchar(8) COLLATE "pg_catalog"."default"   NOT NULL
)
;

COMMENT ON COLUMN "permissions"."role" IS 'role';
COMMENT ON COLUMN "permissions"."resource" IS 'resource';
COMMENT ON COLUMN "permissions"."action" IS 'action';

-- ----------------------------
-- Records of permissions
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS "roles";
CREATE TABLE "roles"
(
    "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
    "role"     varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

COMMENT ON COLUMN "roles"."username" IS 'username';
COMMENT ON COLUMN "roles"."role" IS 'role';

-- ----------------------------
-- Records of roles
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS "tenant_capacity";
CREATE TABLE "tenant_capacity"
(
    "id"                int8                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"         varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
    "quota"             int8                                        NOT NULL DEFAULT 0,
    "usage"             int8                                        NOT NULL DEFAULT 0,
    "max_size"          int8                                        NOT NULL DEFAULT 0,
    "max_aggr_count"    int8                                        NOT NULL DEFAULT 0,
    "max_aggr_size"     int8                                        NOT NULL DEFAULT 0,
    "max_history_count" int8                                        NOT NULL DEFAULT 0,
    "gmt_create"        timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "gmt_modified"      timestamp(6)                                NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

COMMENT ON COLUMN "tenant_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "tenant_capacity"."tenant_id" IS 'Tenant ID';
COMMENT ON COLUMN "tenant_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "tenant_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "tenant_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "tenant_capacity"."max_aggr_count" IS '聚合子配置最大个数';
COMMENT ON COLUMN "tenant_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "tenant_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "tenant_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "tenant_capacity"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "tenant_capacity" IS '租户容量信息表';

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS "tenant_info";
CREATE TABLE "tenant_info"
(
    "id"            int8                                        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kp"            varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
    "tenant_id"     varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "tenant_name"   varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "tenant_desc"   varchar(256) COLLATE "pg_catalog"."default",
    "create_source" varchar(32) COLLATE "pg_catalog"."default",
    "gmt_create"    int8                                        NOT NULL,
    "gmt_modified"  int8                                        NOT NULL
)
;

COMMENT ON COLUMN "tenant_info"."id" IS 'id';
COMMENT ON COLUMN "tenant_info"."kp" IS 'kp';
COMMENT ON COLUMN "tenant_info"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "tenant_info"."tenant_name" IS 'tenant_name';
COMMENT ON COLUMN "tenant_info"."tenant_desc" IS 'tenant_desc';
COMMENT ON COLUMN "tenant_info"."create_source" IS 'create_source';
COMMENT ON COLUMN "tenant_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "tenant_info"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "tenant_info" IS 'tenant_info';

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "users";
CREATE TABLE "users"
(
    "username" varchar(50) COLLATE "pg_catalog"."default"  NOT NULL,
    "password" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
    "enabled"  boolean                                     NOT NULL
)
;

COMMENT ON COLUMN "users"."username" IS 'username';
COMMENT ON COLUMN "users"."password" IS 'password';
COMMENT ON COLUMN "users"."enabled" IS 'enabled';

-- ----------------------------
-- Indexes structure for table config_info
-- ----------------------------
CREATE UNIQUE INDEX "config_info_data_id_group_id_tenant_id_idx" ON "config_info" USING btree (
                                                                                               "data_id"
                                                                                               COLLATE "pg_catalog"."default"
                                                                                               "pg_catalog"."text_ops"
                                                                                               ASC NULLS LAST,
                                                                                               "group_id"
                                                                                               COLLATE "pg_catalog"."default"
                                                                                               "pg_catalog"."text_ops"
                                                                                               ASC NULLS LAST,
                                                                                               "tenant_id"
                                                                                               COLLATE "pg_catalog"."default"
                                                                                               "pg_catalog"."text_ops"
                                                                                               ASC NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table config_info
-- ----------------------------


-- ----------------------------
-- Indexes structure for table config_info_beta
-- ----------------------------
CREATE UNIQUE INDEX "config_info_beta_data_id_group_id_tenant_id_idx" ON "config_info_beta" USING btree (
                                                                                                         "data_id"
                                                                                                         COLLATE "pg_catalog"."default"
                                                                                                         "pg_catalog"."text_ops"
                                                                                                         ASC NULLS LAST,
                                                                                                         "group_id"
                                                                                                         COLLATE "pg_catalog"."default"
                                                                                                         "pg_catalog"."text_ops"
                                                                                                         ASC NULLS LAST,
                                                                                                         "tenant_id"
                                                                                                         COLLATE "pg_catalog"."default"
                                                                                                         "pg_catalog"."text_ops"
                                                                                                         ASC NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table config_info_beta
-- ----------------------------


-- ----------------------------
-- Indexes structure for table config_info_gray
-- ----------------------------
CREATE INDEX "config_info_gray_data_id_gmt_modified_idx" ON "config_info_gray" USING btree (
                                                                                            "data_id"
                                                                                            COLLATE "pg_catalog"."default"
                                                                                            "pg_catalog"."text_ops" ASC
                                                                                            NULLS LAST,
                                                                                            "gmt_modified"
                                                                                            "pg_catalog"."timestamp_ops"
                                                                                            ASC NULLS LAST
    );
CREATE UNIQUE INDEX "config_info_gray_data_id_group_id_tenant_id_gray_name_idx" ON "config_info_gray" USING btree (
                                                                                                                   "data_id"
                                                                                                                   COLLATE "pg_catalog"."default"
                                                                                                                   "pg_catalog"."text_ops"
                                                                                                                   ASC
                                                                                                                   NULLS
                                                                                                                   LAST,
                                                                                                                   "group_id"
                                                                                                                   COLLATE "pg_catalog"."default"
                                                                                                                   "pg_catalog"."text_ops"
                                                                                                                   ASC
                                                                                                                   NULLS
                                                                                                                   LAST,
                                                                                                                   "tenant_id"
                                                                                                                   COLLATE "pg_catalog"."default"
                                                                                                                   "pg_catalog"."text_ops"
                                                                                                                   ASC
                                                                                                                   NULLS
                                                                                                                   LAST,
                                                                                                                   "gray_name"
                                                                                                                   COLLATE "pg_catalog"."default"
                                                                                                                   "pg_catalog"."text_ops"
                                                                                                                   ASC
                                                                                                                   NULLS
                                                                                                                   LAST
    );
CREATE INDEX "config_info_gray_gmt_modified_idx" ON "config_info_gray" USING btree (
                                                                                    "gmt_modified"
                                                                                    "pg_catalog"."timestamp_ops" ASC
                                                                                    NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table config_info_gray
-- ----------------------------

-- ----------------------------
-- Indexes structure for table config_info_tag
-- ----------------------------
CREATE UNIQUE INDEX "config_info_tag_data_id_group_id_tenant_id_tag_id_idx" ON "config_info_tag" USING btree (
                                                                                                              "data_id"
                                                                                                              COLLATE "pg_catalog"."default"
                                                                                                              "pg_catalog"."text_ops"
                                                                                                              ASC NULLS
                                                                                                              LAST,
                                                                                                              "group_id"
                                                                                                              COLLATE "pg_catalog"."default"
                                                                                                              "pg_catalog"."text_ops"
                                                                                                              ASC NULLS
                                                                                                              LAST,
                                                                                                              "tenant_id"
                                                                                                              COLLATE "pg_catalog"."default"
                                                                                                              "pg_catalog"."text_ops"
                                                                                                              ASC NULLS
                                                                                                              LAST,
                                                                                                              "tag_id"
                                                                                                              COLLATE "pg_catalog"."default"
                                                                                                              "pg_catalog"."text_ops"
                                                                                                              ASC NULLS
                                                                                                              LAST
    );

-- ----------------------------
-- Primary Key structure for table config_info_tag
-- ----------------------------


-- ----------------------------
-- Indexes structure for table config_tags_relation
-- ----------------------------
CREATE UNIQUE INDEX "config_tags_relation_id_tag_name_tag_type_idx" ON "config_tags_relation" USING btree (
                                                                                                           "id"
                                                                                                           "pg_catalog"."int8_ops"
                                                                                                           ASC NULLS
                                                                                                           LAST,
                                                                                                           "tag_name"
                                                                                                           COLLATE "pg_catalog"."default"
                                                                                                           "pg_catalog"."text_ops"
                                                                                                           ASC NULLS
                                                                                                           LAST,
                                                                                                           "tag_type"
                                                                                                           COLLATE "pg_catalog"."default"
                                                                                                           "pg_catalog"."text_ops"
                                                                                                           ASC NULLS
                                                                                                           LAST
    );
CREATE INDEX "config_tags_relation_tenant_id_idx" ON "config_tags_relation" USING btree (
                                                                                         "tenant_id"
                                                                                         COLLATE "pg_catalog"."default"
                                                                                         "pg_catalog"."text_ops" ASC
                                                                                         NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table config_tags_relation
-- ----------------------------


-- ----------------------------
-- Indexes structure for table group_capacity
-- ----------------------------
CREATE UNIQUE INDEX "group_capacity_group_id_idx" ON "group_capacity" USING btree (
                                                                                   "group_id"
                                                                                   COLLATE "pg_catalog"."default"
                                                                                   "pg_catalog"."text_ops" ASC NULLS
                                                                                   LAST
    );

-- ----------------------------
-- Primary Key structure for table group_capacity
-- ----------------------------

-- ----------------------------
-- Indexes structure for table his_config_info
-- ----------------------------
CREATE INDEX "his_config_info_data_id_idx" ON "his_config_info" USING btree (
                                                                             "data_id" COLLATE "pg_catalog"."default"
                                                                             "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "his_config_info_gmt_create_idx" ON "his_config_info" USING btree (
                                                                                "gmt_create"
                                                                                "pg_catalog"."timestamp_ops" ASC NULLS
                                                                                LAST
    );
CREATE INDEX "his_config_info_gmt_modified_idx" ON "his_config_info" USING btree (
                                                                                  "gmt_modified"
                                                                                  "pg_catalog"."timestamp_ops" ASC NULLS
                                                                                  LAST
    );

-- ----------------------------
-- Primary Key structure for table his_config_info
-- ----------------------------


-- ----------------------------
-- Indexes structure for table permissions
-- ----------------------------
CREATE UNIQUE INDEX "permissions_role_resource_action_idx" ON "permissions" USING btree (
                                                                                         "role"
                                                                                         COLLATE "pg_catalog"."default"
                                                                                         "pg_catalog"."text_ops" ASC
                                                                                         NULLS LAST,
                                                                                         "resource"
                                                                                         COLLATE "pg_catalog"."default"
                                                                                         "pg_catalog"."text_ops" ASC
                                                                                         NULLS LAST,
                                                                                         "action"
                                                                                         COLLATE "pg_catalog"."default"
                                                                                         "pg_catalog"."text_ops" ASC
                                                                                         NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table roles
-- ----------------------------
CREATE UNIQUE INDEX "roles_username_role_idx" ON "roles" USING btree (
                                                                      "username" COLLATE "pg_catalog"."default"
                                                                      "pg_catalog"."text_ops" ASC NULLS LAST,
                                                                      "role" COLLATE "pg_catalog"."default"
                                                                      "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table tenant_capacity
-- ----------------------------
CREATE UNIQUE INDEX "tenant_capacity_tenant_id_idx" ON "tenant_capacity" USING btree (
                                                                                      "tenant_id"
                                                                                      COLLATE "pg_catalog"."default"
                                                                                      "pg_catalog"."text_ops" ASC NULLS
                                                                                      LAST
    );

-- ----------------------------
-- Primary Key structure for table tenant_capacity
-- ----------------------------


-- ----------------------------
-- Indexes structure for table tenant_info
-- ----------------------------
CREATE UNIQUE INDEX "tenant_info_kp_tenant_id_idx" ON "tenant_info" USING btree (
                                                                                 "kp" COLLATE "pg_catalog"."default"
                                                                                 "pg_catalog"."text_ops" ASC NULLS LAST,
                                                                                 "tenant_id"
                                                                                 COLLATE "pg_catalog"."default"
                                                                                 "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "tenant_info_tenant_id_idx" ON "tenant_info" USING btree (
                                                                       "tenant_id" COLLATE "pg_catalog"."default"
                                                                       "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table tenant_info
-- ----------------------------


-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------

