name: Docker Build and Push

on:
  push:
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [oracle,mssql,dm,postgresql]
        java: [8]
    steps:
      - name: set version
        id: version_set
        run: |
          echo "NACOS_VERSION=${GITHUB_REF#$'refs/tags/v'}" >> $GITHUB_ENV
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'
      - name: "Cache Maven Repos"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Maven install
        run: mvn clean install -DskipTests

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: datasource-plugin-ext.Dockerfile
          push: true
          tags: ${{ NACOS_VERSION }}
          labels: "Nacos ${{ NACOS_VERSION }} "
          build-args: |
            DATASOURCE_PLUGIN=${{ matrix.database }}
